### ISSUE TITLE
How to get simple name from device advertisment

### ISSUE THREAD

**Issue by enochc** [laptou/bluez-rs#21]
I'm really interested in the repository for a project I'm working on. Is it possible to filter a device "simple name" in the discovery process? I know that's available in the advertisement data.  Does anyone have an example how to to pair a device?

**Comment by enochc** [comment]
Oh I found the name in the eid data, not sure what the best parsing solution is to get it.

**Comment by laptou** [comment]
A pull request for parsing EIR data (#19) is in the works right now, actually.

**Comment by enochc** [comment]
Brilliant! thank you, sorry I missed that.
