### ISSUE TITLE
Question about sending commands

### ISSUE THREAD

**Issue by EthanYidong** [laptou/bluez-rs#24]
Sorry for bothering again, but I'm a bit confused on how this crate sends HCI commands. The bytes generated here:
https://github.com/laptou/bluez-rs/blob/01ee38b4c1b42359afedec1d6f8f1e3fa2e5ed02/src/interface/request.rs#L13-L24

don't seem to line up with the C library [here](https://github.com/bluez/bluez/blob/1f4ec8fb9d36fb7678385fd631459d80b57fc662/lib/hci.c#L1082-L1110). Would you mind explaining where I can find documentation about the type of data that can be sent to the HCI socket/stream?

**Comment by laptou** [comment]
This library doesn't send raw HCI commands, it only sends commands to the management API, whose format is specified [here](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/mgmt-api.txt#n153).
