### ISSUE TITLE
Why does discover need `sudo`?

### ISSUE THREAD

**Issue by WhyNotHugo** [laptou/bluez-rs#28]
I notice that `blueman-manager` can discover devices with bluez without being root. Why does bluez-rs need `sudo` permissions for discovering?

**Comment by laptou** [comment]
Technically, it needs the `CAP_NET_RAW` capability. I suspect that system utilities are able to get this capability automatically via setuid or a similar mechanism, but that's not really practical for development purposes.

**Comment by eduardoheleno** [comment]
How can i use sudo to execute de start_discovery function?

**Comment by WhyNotHugo** [comment]
Ah, indeed, other tools simply rely on [`bluez`](http://www.bluez.org/) which entirely runs as root.

**Comment by WhyNotHugo** [comment]
@EduardoPD1921 `sudo` can only be used to elevate the privileges of an entire process, not just one function. If you have a larger program that you'd rather not elevate, you might need a SUID helper or something like that.
