### ISSUE TITLE
Panic after device connect

### ISSUE THREAD

**Issue by timvisee** [laptou/bluez-rs#3]
After confirming a connection request, I'm getting a panic happening at the following line:

https://github.com/laptou/bluez-rs/blob/02ec3fc08f6f10e4717ed7dfa3e0a2f3c2354676/src/interface/response.rs#L75

This apparently comes up when processing the `NewLongTermKey` event.

`buf.get_u8()` gives a `3`. The `FromPrimitive` helper can't parse this into a `LongTermKeyType` which is why it panics.

Any idea what is going on?

**Comment by laptou** [comment]
Got it. I implemented this according to the [BlueZ spec](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/mgmt-api.txt) and it defines the long term key type enum inconsistently for different events:

https://github.com/Vudentz/BlueZ/blob/4e926f8e3ef2e3321f9b169db54ec256d9b41207/doc/mgmt-api.txt#L859-L862

https://github.com/Vudentz/BlueZ/blob/4e926f8e3ef2e3321f9b169db54ec256d9b41207/doc/mgmt-api.txt#L3108-L3114

So I didn't see the version of the enum that includes the value `3`.

**Comment by timvisee** [comment]
Awesome. Thanks for the quick fix!
