### ISSUE TITLE
IoCapability values are incorrect

### ISSUE THREAD

**Issue by timvisee** [laptou/bluez-rs#4]
The `IoCapability` values seem to be incorrect. I believe their values should start from `0`, not `1`.

https://github.com/laptou/bluez-rs/blob/02ec3fc08f6f10e4717ed7dfa3e0a2f3c2354676/src/client/params.rs#L62-L70

I couldn't really find proper documentation on this. But here's some source that specifies these:

https://github.com/redboltz/bluez/blob/bca184dd8fc86718984b204f121dc35196ecece2/tools/parser/smp.c#L49-L54

**Comment by laptou** [comment]
Seems like you're right, [this post](https://www.bluetooth.com/blog/bluetooth-pairing-part-1-pairing-feature-exchange/) suggests that `IoCapability::DisplayOnly` is `0` as well.
