### ISSUE TITLE
Could not find matching version of bitvec

### ISSUE THREAD

**Issue by tpoliaw** [laptou/bluez-rs#7]
I have created a new rust project (`cargo init` with cargo version 1.42.0) and added `bluez = "0.1.2"` as a dependency as written on the crates.io page. With no other changes to the helloWorld example, I get a build error saying

        Updating crates.io index
    error: failed to select a version for the requirement `bitvec = "^0.16"`
      candidate versions found which didn't match: 0.17.4
      location searched: crates.io index
    required by package `bluez v0.1.2`
        ... which is depended on by `tests v0.1.0 (/tmp/tests)`

Cloning this repo and running the examples worked fine.

It looks like all bitvec v0.16 crates have been yanked.

**Comment by fengyc** [comment]
Blocked by the same issue
```
error: failed to select a version for the requirement `bitvec = "^0.16"`
  candidate versions found which didn't match: 0.17.4
```
